namespace Domain.Entities
{
    /// <summary>
    /// Represents a request to cancel an existing workflow. 
    /// This class encapsulates the necessary data required to initiate the cancellation of a workflow, typically a leave request.
    /// </summary>
    public class CancelLeaveRequest
    {
        /// <summary>
        /// Gets or sets the unique identifier of the workflow to be canceled.
        /// This identifier is typically a string generated by the workflow engine (WorkflowCore) when the workflow is started.
        /// It is used to uniquely identify the workflow instance that needs to be terminated.
        /// </summary>
        public required string WorkflowId { get; set; }

        /// <summary>
        /// Gets or sets the unique identifier of the user who is requesting the cancellation.
        /// This could be the ID of the employee who initially submitted the request or a manager who has the authority to cancel the workflow.
        /// </summary>
        public required Guid UserId { get; set; }

        /// <summary>
        /// Gets or sets the reason for the cancellation.
        /// This field is optional and allows the user to provide an explanation or justification for why the workflow is being canceled.
        /// The reason could be logged or stored for auditing purposes, making it easier to track why certain workflows were terminated.
        /// </summary>
        public string? Reason { get; set; }
    }
}
